### ISSUE TITLE
dangling symbolic links

### ISSUE THREAD

**Issue by chaudhuri** [whitequark/opam-cross-windows#1]
There are symbolic links in `~/.opam/packages/ocaml-windows64/ocaml-windows64.4.02.3/files` that point to `../../ocaml-windows32.4.02.3/files`. However, `ocaml-windows32` need not be installed on an amd64 host/windows64 target, which is the default selected by `opam install ocaml-windows` (as recommended in the `README.md`).

Because of these dangling symbolic links, `opam update` stops working with the following error message:

>     % opam update
>     
>     =-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
>     [windows] git://github.com/whitequark/opam-cross-windows already up-to-date
>     [default] /home/kaustuv/hacking/opam-repository synchronized
>     Fatal error:
>     Sys_error("/home/kaustuv/.opam/packages/ocaml-windows64/ocaml-windows64.4.02.3/files/windows.conf.in: No such file or directory")

In case it is relevant:

>     $ opam --version
>     1.2.2
>     $ ocamlc -vnum
>     4.02.3
>     $ uname -a
>     Linux wash3 3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux

**Comment by whitequark** [comment]
Ahh, I misunderstood how symlinks worked in repos.
