### ISSUE TITLE
Tag/branch for last 4.02.3 commit

### ISSUE THREAD

**Issue by hcarty** [whitequark/opam-cross-windows#16]
I think a6fb59f44f2b6d409c9fa333869b659b2a989c6d is the last commit before the move to 4.04.0.  Could you add a tag or branch for that commit?  I can use specific commit hashes when necessary but a tag would be helpful as a quick reference point.

Thanks for the flurry of updates moving to 4.04.0!

**Comment by whitequark** [comment]
Done

**Comment by whitequark** [comment]
There's actually no real reason we can't have 4.02.3 and 4.04.0 side by side, I just didn't get paid to debug that. If you want you can simply bring 4.02.3 back, and make sure it works.

**Comment by hcarty** [comment]
Thank you very much.  If I get a chance to do so I will.
