### ISSUE TITLE
Unable to pin ocamlbuild as described in README

### ISSUE THREAD

**Issue by hcarty** [whitequark/opam-cross-windows#17]
It looks like the repo is private or otherwise hidden.  The web interface gives a 404 and the git CLI prompts for a username + password.

**Comment by hcarty** [comment]
Ah, I see - I'm guessing that it became unnecessary after https://github.com/ocaml/ocamlbuild/pull/125 was merged.  I'll trying pinning to upstream ocamlbuild#master instead.

**Comment by whitequark** [comment]
Fixed in master.

**Comment by hcarty** [comment]
Thank you!
