### ISSUE TITLE
'Unsupported relocation kind 0003' when trying to build zmq-windows with a static MXE

### ISSUE THREAD

**Issue by hcarty** [whitequark/opam-cross-windows#23]
I'm working on a zeromq package/installation for MXE.  It works fine with opam-cross-windows when building against a dynamically linked MXE but not statically (`MXE_TARGETS:=x86_64-w64-mingw32.static`)

Do you have any suggestions on where to start looking?  Based on https://github.com/alainfrisch/flexdll/issues/29 hinting that SEH could be an issue I tried a fresh MXE build with `gcc.mk` patched to include `--enable-sjlj-exceptions` but I get the same error aside from a change in the problematic gcc symbol name from `__gxx_personality_seh0` to `__gxx_personality_sj0`

The error when building `zmq-windows` with OCaml 4.04.0 from opam-cross-windows:
```
/home/hcarty/.opam/4.04.0/bin/ocamlfind ocamlmklib -o src/ZMQ_stubs -lzmq src/caml_zmq_stubs.o src/socket.o src/context.o src/fail.o src/poll.o
+ /home/hcarty/.opam/4.04.0/bin/ocamlfind ocamlmklib -o src/ZMQ_stubs -lzmq src/caml_zmq_stubs.o src/socket.o src/context.o src/fail.o src/poll.o
** Fatal error: Unsupported relocation kind 0003 for __gxx_personality_seh0 in /home/hcarty/mxe/usr/x86_64-w64-mingw32.static/lib/libzmq.a(src_libzmq_la-clock.o/
```
followed by the rest of the `.o` files in the libzmq.a archive.

**Comment by whitequark** [comment]
Not really any suggestions. Perhaps use a 32-bit build if you can. I can probably fix flexdll but not quickly and this is not a priority for me. I'd be willing to do this as a contractual item at my usual rate but I'm not sure if this will fit your goals.

**Comment by whitequark** [comment]
(The above assumes zeromq actually uses exceptions; if not just rebuild with `-fno-exceptions`, but that seems unlikely to work.)

**Comment by hcarty** [comment]
Finally got back to this and to my delight `-fno-exceptions` did the trick.  Now there are linking issues with `libzmq.a` but that doesn't seem to be OCaml-related.

Thank you for the pointer!

**Comment by whitequark** [comment]
No, this absolutely doesn't mean the issue is solved. Now, assuming zeromq actually *does* use exceptions, it will simply crash the entire process instead.

**Comment by whitequark** [comment]
I went through the ZeroMQ source and it doesn't use exceptions as far as I can see, so the fix is fine.

**Comment by hcarty** [comment]
@whitequark Apologies - I should have been clearer.  I also did a search through zeromq's source for anything referencing exceptions before trying the compilation option.
