### ISSUE TITLE
ctypes-windows: ffi.h not found

### ISSUE THREAD

**Issue by mark5ml** [whitequark/opam-cross-windows#24]
After following your description to install ocaml-windows, I tried to install ctypes-windows using

`# opam install ctypes-windows`

I get the following error in the end.

```
# cd _build/src/ctypes-foreign-base && ocamlfind -toolchain windows ocamlc -c -package bytes   -ccopt -std=c99 -ccopt -Wall -ccopt -g -ccopt -I -ccopt /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes -ccopt -I -ccopt /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/tests -o ffi_call_stubs.o -principal -short-paths -g /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes-foreign-base/ffi_call_stubs.c
# Makefile.rules:111: recipe for target '_build/src/ctypes-foreign-base/ffi_call_stubs.o' failed
### stderr ###
# [...]
# Warning 52: Code should not depend on the actual values of
# this constructor's arguments. They are only for information
# and may change in future versions. (See manual section 8.5)
# /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes-foreign-base/dl_stubs.c: In function ‘ctypes_win32_dlopen’:
# /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes-foreign-base/dl_stubs.c:246:11: warning: ‘ec’ may be used uninitialized in this function [-Wmaybe-uninitialized]
#        ret=get_tagged_error_msg(ec);
#            ^
# /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes-foreign-base/ffi_call_stubs.c:22:17: fatal error: ffi.h: No such file or directory
# compilation terminated.
# make: *** [_build/src/ctypes-foreign-base/ffi_call_stubs.o] Error 2
```

Running `ocamlfind` with `-verbose` shows the compiler call that causes the problem.

```
x86_64-w64-mingw32-gcc -O2 -mms-bitfields -fno-strict-aliasing -Wall -c -g -std=c99 -Wall -g -I /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes -I /home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/tests '-I/home/mark/.opam/4.04.0/windows-sysroot/lib/bytes' -I'/home/mark/.opam/4.04.0/windows-sysroot/lib/ocaml' '/home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes-foreign-base/ffi_call_stubs.c'
/home/mark/.opam/4.04.0/build/ctypes-windows.0.11.0/src/ctypes-foreign-base/ffi_call_stubs.c:22:17: fatal error: ffi.h: No such file or directory
compilation terminated.
```

`ffi.h` exists in `/usr/include/x86_64-linux-gnu` but that I suppose this is not what mingw is looking for. I am running Ubuntu 16.04. Which package do I need to install to have ffi for mingw?

**Comment by hcarty** [comment]
I'm not sure what the Ubuntu package name is, but you'd need a mingw libffi package. A quick search through the Ubuntu 16.04 package list doesn't show anything obvious.

If a suitable package does not exist for Ubuntu then you have the option of using http://mxe.cc as your C cross-compiler.

**Comment by whitequark** [comment]
There is no Ubuntu package for cross-libffi. You may compile it yourself if you want, but note that in that case you will also need to compile your own compiler to embed the paths to your sysroot into it. Since this is pretty much what MXE does, it is probably not worth the hassle.

Using the Ubuntu-provided MinGW compilers only really works for the simplest applications (though it is still valuable for e.g. utilities with no external C dependencies).

**Comment by mark5ml** [comment]
Thanks for the explanation. I will use MXE then.
