### ISSUE TITLE
camlimages-windows hosted on MacOSX can't find freetype headers

### ISSUE THREAD

**Issue by markghayden** [whitequark/opam-cross-windows#3]
camlimages-windows fails with the error below.  It looks like it is not picking up freetype2 headers in /usr/local/include/freetype2 (installed via homebrew).

--Mark

```
The following actions will be performed:
  - install camlimages-windows 4.2.1
Do you want to continue ? [Y/n] 
y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[camlimages-windows.4.2.1] https://bitbucket.org/camlspotter/camlimages/get/4.2.1.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of camlimages-windows failed at "ocamlfind -toolchain
        windows ocamlc -I /freetype2 src/ftintf.c".
Processing  1/1: [camlimages-windows: ocamlfind windows]
#=== ERROR while installing camlimages-windows.4.2.1 ==========================#
# opam-version 1.2.2
# os           darwin
# command      ocamlfind -toolchain windows ocamlc -I /freetype2 src/ftintf.c
# path         /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1
# compiler     4.02.3
# exit-code    2
# env-file     /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1/camlimages-windows-22733-d0f245.env
# stdout-file  /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1/camlimages-windows-22733-d0f245.out
# stderr-file  /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1/camlimages-windows-22733-d0f245.err
### stderr ###
# src/ftintf.c:24:22: fatal error: ft2build.h: No such file or directory
#  #include <ft2build.h>
#                       ^
# compilation terminated.



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install camlimages-windows 4.2.1
No changes have been performed

=-=- camlimages-windows.4.2.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext camlimages-windows.4.2.1' may help you find the correct
   installation for your system.
```

**Comment by whitequark** [comment]
`ocamlfind -toolchain windows ocamlc -I /freetype2 src/ftintf.c`
Here's the problem:
`-I /freetype2`

**Comment by whitequark** [comment]
Hang on. Why are you expecting `camlimages-windows` to pick up *anything* installed via Homebrew? That's not how cross-compilation works; nothing installed in the host environment is relevant.

**Comment by markghayden** [comment]
I agree.  That should be something like "-I /usr/local/include/freetype2", at least on systems using home-brew to install freetype.

**Comment by markghayden** [comment]
Good point!  That should be coming from MXE.  All the other packages we use seem to be picking up MXE, except this.

**Comment by whitequark** [comment]
So... these two commands fail: https://github.com/whitequark/opam-cross-windows/blob/master/packages/conf-gcc-windows.1/opam#L6-L7

Could you try running them manually? I can set up MXE on my OS X VM but it'll take a while.

**Comment by whitequark** [comment]
Of course, replace `%{conf-gcc-windows64:prefix}%` with the prefix leading to your `gcc` inside MXE.

**Comment by markghayden** [comment]
Coming back to this, I think the issue is that freetype is being installed in a freetype2 sub-directory of the include.  Adding the symbolic links below makes it work.  Is there a better fix?


sakhalin% pwd
/Users/mhayden/plotter/proj/mxe/mxe/usr/x86_64-w64-mingw32.shared/include
sakhalin% ln -s freetype2/
freetype/   ft2build.h  
sakhalin% ln -s freetype2/freetype .
sakhalin% ln -s freetype2/ft2build.h .

**Comment by whitequark** [comment]
Hm, this freetype idiosyncrasy is supposed to be handled here: https://github.com/whitequark/opam-cross-windows/blob/master/packages/camlimages-windows.4.2.1/opam#L88-L90

**Comment by whitequark** [comment]
Specifically, `"-I" "%{conf-gcc-windows:c-include}%/freetype2"` fails as you get a `-I /freetype2` flag, which means that the variable `conf-gcc-windows:c-include` is empty. This is set here: https://github.com/whitequark/opam-cross-windows/blob/master/packages/conf-gcc-windows.1/opam#L4-L7. Something on OS X is behaving funky, probably because I have an implicit GNU assumption somewhere in that horrible script.

**Comment by whitequark** [comment]
Oh. 
```
user@users-iMac:~$ readlink -f x
readlink: illegal option -- f
```

There's... no good way to make everything work without `readlink -f`. There are no good solutions to that either (see https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac). Please install GNU readlink and make sure it's in PATH as `readlink`

**Comment by markghayden** [comment]
Hi Peter,

I installed coreutils from Homebrew and linked /opt/local/gin/greadlink to ~/bin/link.  It still won’t install camlimages-windows.  Am I doing something wrong?

—Mark


++ which readlink
+ ls -l /Users/mhayden/bin/readlink
lrwxrwxr-x  1 mhayden  501  24 Apr 30 15:03 /Users/mhayden/bin/readlink -> /opt/local/bin/greadlink
+ readlink -f .
/Users/mhayden/plotter/proj/mxe/ocw
+ opam install yojson-windows flexdll-windows camlbz2-windows camlzip-windows proj4-windows expat-windows camlimages-windows
[NOTE] Package yojson-windows is already installed (current version is 1.3.2).
[NOTE] Package flexdll-windows is already installed (current version is 0.34).
[NOTE] Package camlbz2-windows is already installed (current version is 0.6.0).
[NOTE] Package camlzip-windows is already installed (current version is 1.05).
[NOTE] Package proj4-windows is already installed (current version is 0.9.1).
[NOTE] Package expat-windows is already installed (current version is 0.9.1).
The following actions will be performed:
  - install camlimages-windows 4.2.1
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[camlimages-windows.4.2.1] https://bitbucket.org/camlspotter/camlimages/get/4.2.1.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of camlimages-windows failed at "ocamlfind -toolchain windows ocamlc -I /freetype2 src/ftintf.c".
Processing  1/1: [camlimages-windows: ocamlfind windows]
#=== ERROR while installing camlimages-windows.4.2.1 ==========================#
# opam-version 1.2.2
# os           darwin
# command      ocamlfind -toolchain windows ocamlc -I /freetype2 src/ftintf.c
# path         /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1
# compiler     4.02.3
# exit-code    2
# env-file     /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1/camlimages-windows-67103-d0f245.env
# stdout-file  /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1/camlimages-windows-67103-d0f245.out
# stderr-file  /Users/mhayden/.opam/4.02.3/build/camlimages-windows.4.2.1/camlimages-windows-67103-d0f245.err
### stderr ###
# src/ftintf.c:24:22: fatal error: ft2build.h: No such file or directory
#  #include <ft2build.h>
#                       ^
# compilation terminated.



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install camlimages-windows 4.2.1
No changes have been performed

=-=- camlimages-windows.4.2.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext camlimages-windows.4.2.1' may help you
   find the correct installation for your system.
sakhalin%

**Comment by whitequark** [comment]
> I installed coreutils from Homebrew and linked /opt/local/gin/greadlink to ~/bin/link.  It still won’t install camlimages-windows.  Am I doing something wrong?

Yeah--as I understand the symlink is named `greadlink`, it should be `readlink`. I'll look into making the opam build script look for `greadlink` on OS X later, but such conditions are irritating to implement due to some of opam's design choices.

**Comment by markghayden** [comment]
I named the symlink readlink but things still didn’t work.  If readlink is required, maybe the install should fail if it is missing or doesn’t support ‘-f’ option?

—Mark

++ which readlink
+ ls -l /Users/mhayden/bin/readlink
lrwxrwxr-x  1 mhayden  501  24 Apr 30 15:03 /Users/mhayden/bin/readlink -> /opt/local/bin/greadlink
+ readlink -f .
/Users/mhayden/plotter/proj/mxe/ocw

**Comment by whitequark** [comment]
Sorry--I neglected to mention. After installing readlink you need to reinstall `conf-gcc-windows`. That should fix it.

**Comment by markghayden** [comment]
Ok; that worked.  Thanks!  —M
