### ISSUE TITLE
Sys.win32 = false in cross-compiled executables 

### ISSUE THREAD

**Issue by mfp** [whitequark/opam-cross-windows#4]
Found this when testing the Lwt (cross-)port (it kills all programs linked against lwt.unix, since it uses Sys.win32 during initialization):

    $ cat ostype.ml 
    open Printf

    let () =
      printf "os_type: %S\n" Sys.os_type;
      printf "win32: %b\n" Sys.win32;
      printf "unix: %b\n" Sys.unix;
      printf "cygwin: %b\n" Sys.cygwin;
      printf "word_size: %d\n" Sys.word_size;
      printf "big_endian: %b\n" Sys.big_endian

    $ ocamlfind -toolchain windows ocamlopt -o ostype.exe ostype.ml
    ... later, on windows...    
    $ ./ostype.exe 
    os_type: "Win32"
    win32: false
    unix: true
    cygwin: false
    word_size: 32
    big_endian: false

This is seemingly impossible since the same OCAML_OS_TYPE value is used in sys.c to return the os_type value and perform the win32() check (which is just strcmp(OCAML_OS_TYPE, "Win32") ).

**Comment by whitequark** [comment]
The compiler has a compile-time optimization that equates `Sys.win32` to a constant directly, to aid in dead code removal.

**Comment by mfp** [comment]
I see,  https://github.com/ocaml/ocaml/blob/trunk/asmcomp/closure.ml#L467

**Comment by whitequark** [comment]
Yes. I think as a first approximation we can patch that directly. Would you prepare a PR?
