### ISSUE TITLE
build failure for ocaml-windows with the 4.02.3+32bit compiler

### ISSUE THREAD

**Issue by oandrieu** [whitequark/opam-cross-windows#6]
When running `opam install ocaml-windows` on a linux x86_64 host using the 4.02.3+32bit switch, `ocaml-windows64` gets built and it fails:
 ```
# /home/oandrieu/.opam/4.02.3+32bit/bin/ocamlrun boot/ocamlc -nostdlib -I boot -strict-sequence -w +33..39+48 -warn-error A -bin-annot -I utils -I parsing -I typing -I bytecomp -I asmcomp -I driver -I toplevel -c asmcomp/selection.ml
# Makefile.nt:723: recipe for target 'asmcomp/selection.cmo' failed
### stderr ###
# File "asmcomp/selection.ml", line 125, characters 49-59:
# Error: Integer literal exceeds the range of representable integers of type int
```
and indeed:
```
method is_immediate n = n <= 0x7FFFFFFF && n >= -0x80000000
```
doesn't seem to good with 31bits ints.

Shouldn't `opam install ocaml-windows` be installing `ocaml-windows32` instead ?

**Comment by whitequark** [comment]
That seems like an opam bug, since ocaml-windows64 declares:
```
available: [ ocaml-version = "4.02.3" & arch = "x86_64" ]
```

Can you please report this against opam? The workaround is, of course, to install ocaml-windows32 manually.

**Comment by whitequark** [comment]
Hm, no, wait, I misunderstood how the `arch` variable works. Let me fix this.

**Comment by oandrieu** [comment]
Seems good now, thanks !
